name: Generate Keystore - First time only
on:
  workflow_dispatch:
    inputs:
      password:
        description: 'ضع كلمة سر للمفتاح (احفظها)'
        required: true
        default: 'Taqweem123'

jobs:
  gen:
    runs-on: ubuntu-latest
    steps:
      - name: Generate keystore
        run: |
          keytool -genkey -v -keystore release.jks -keyalg RSA -keysize 2048 -validity 10000 -alias taqweem -storepass ${{ github.event.inputs.password }} -keypass ${{ github.event.inputs.password }} -dname "CN=Taqweem, OU=App, O=Fadol, L=Tripoli, ST=North, C=LB"
          ls -lh release.jks
          base64 release.jks > keystore_base64.txt
          echo "=== انسخ هذا النص كامل ==="
          cat keystore_base64.txt

      - name: Upload keystore files
        uses: actions/upload-artifact@v4
        with:
          name: keystore-files-KEEP-SAFE
          path: |
            release.jks
            keystore_base64.txt
